### ISSUE TITLE
The previous request variable pr isn't updating during a single session.

### ISSUE THREAD

**Issue by emanrow** [0ut0flin3/openai-davinci003-python-speech#3]
There is a logic flow problem with the memories file: It loads fine, and dumps fine at the end, but each successive request only sends the original request, stored in the variable `pr`, plus the latest human request.

You can test this out by asking the AI something, then asking it what its previous answer was. It has no clue.

If you update `pr` as you go, this is solved and the AI will be fully conversational. I assigned the response to a variable `a`, then update `pr` it with:

`pr = pr+"Human: "+q+"\nAI: "+a+"\n"`

**Comment by erikbye** [comment]
Can you explain which lines of code you inserted where?

With the code as is, with the second response I get the error:

print("Human: "+q)
          ~~~~~~~~~^~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by 0ut0flin3** [comment]
> There is a logic flow problem with the memories file: It loads fine, and dumps fine at the end, but each successive request only sends the original request, stored in the variable `pr`, plus the latest human request.
> 
> You can test this out by asking the AI something, then asking it what its previous answer was. It has no clue.
> 
> If you update `pr` as you go, this is solved and the AI will be fully conversational. I assigned the response to a variable `a`, then update `pr` it with:
> 
> `pr = pr+"Human: "+q+"\nAI: "+a+"\n"`

I'm working on it

**Comment by 0ut0flin3** [comment]
> Can you explain which lines of code you inserted where?
> 
> With the code as is, with the second response I get the error:
> 
> ```
> print("Human: "+q)
>           ~~~~~~~~~^~
> TypeError: can only concatenate str (not "NoneType") to str
> ```
> 
> EDIT: Actually, it crashes after a few seconds with the error above, if I am not speaking into the microphone. Or if I take "too long" to respond.

Yes, it is the main problem/bug, I'm working on it

**Comment by 0ut0flin3** [comment]
> There is a logic flow problem with the memories file: It loads fine, and dumps fine at the end, but each successive request only sends the original request, stored in the variable `pr`, plus the latest human request.
> 
> You can test this out by asking the AI something, then asking it what its previous answer was. It has no clue.
> 
> If you update `pr` as you go, this is solved and the AI will be fully conversational. I assigned the response to a variable `a`, then update `pr` it with:
> 
> `pr = pr+"Human: "+q+"\nAI: "+a+"\n"`

Solved. Thank you
